channels:
  - conda-forge
  - defaults
  - anaconda
  - main
dependencies:
  - aiohappyeyeballs=2.4.3
  - aiohttp=3.10.5
  - aiosignal=1.3.1
  - annotated-types=0.7.0
  - anyio=4.6.2
  - async-timeout=4.0.3
  - attrs=24.2.0
  - blas=1.0
  - bottleneck=1.3.7
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2024.9.24
  - cachetools=5.5.0
  - certifi=2024.8.30
  - cffi=1.17.1
  - charset-normalizer=3.4.0
  - click=8.1.7
  - colorama=0.4.6
  - cryptography=43.0.0
  - exceptiongroup=1.2.0
  - fastapi=0.112.2
  - frozenlist=1.4.0
  - google-ai-generativelanguage=0.6.10
  - google-api-core=2.22.0
  - google-api-python-client=2.149.0
  - google-auth=2.35.0
  - google-auth-httplib2=0.2.0
  - google-generativeai=0.8.3
  - googleapis-common-protos=1.65.0
  - grpcio=1.62.2
  - h11=0.14.0
  - h2=4.1.0
  - hpack=4.0.0
  - httplib2=0.22.0
  - hyperframe=6.0.1
  - idna=3.10
  - libabseil=20240116.2
  - libcxx=19.1.3
  - libffi=3.4.4
  - libgrpc=1.62.2
  - libopenblas=0.3.21
  - libprotobuf=4.25.3
  - libsqlite=3.45.3
  - libzlib=1.2.13
  - llvm-openmp=14.0.6
  - loguru=0.7.2
  - lz4-c=1.9.4
  - multidict=6.1.0
  - ncurses=6.4.20240210
  - numexpr=2.10.1
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openssl=3.3.2
  - pandas=2.2.2
  - pip=24.2
  - proto-plus=1.25.0
  - protobuf=4.25.3
  - pyasn1=0.6.1
  - pyasn1-modules=0.4.1
  - pycparser=2.22
  - pydantic=2.8.2
  - pydantic-core=2.20.1
  - pyopenssl=24.2.1
  - pyparsing=3.2.0
  - pysocks=1.7.1
  - python=3.10.15
  - python-dateutil=2.9.0post0
  - python-dotenv=0.21.0
  - python-tzdata=2023.3
  - pytz=2024.1
  - pyu2f=0.1.5
  - re2=2022.04.01
  - readline=8.2
  - requests=2.32.3
  - rsa=4.9
  - setuptools=75.1.0
  - six=1.16.0
  - sniffio=1.3.0
  - sqlite=3.45.3
  - starlette=0.38.2
  - tk=8.6.14
  - tqdm=4.66.6
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2024b
  - uritemplate=4.1.1
  - urllib3=2.2.3
  - uvicorn=0.20.0
  - wheel=0.44.0
  - xz=5.4.6
  - yarl=1.11.0
  - zlib=1.2.13
  - zstandard=0.23.0
  - zstd=1.5.6
